// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task/task.proto

/*
Package task is a generated protocol buffer package.

It is generated from these files:
	task/task.proto

It has these top-level messages:
	Task
	CreateTaskRequest
	CreateTaskResponse
	FindTasksResponse
*/
package task

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_UNKNOWN   Status = 0
	Status_WAITING   Status = 1
	Status_WORKING   Status = 2
	Status_COMPLETED Status = 3
)

var Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "WAITING",
	2: "WORKING",
	3: "COMPLETED",
}
var Status_value = map[string]int32{
	"UNKNOWN":   0,
	"WAITING":   1,
	"WORKING":   2,
	"COMPLETED": 3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Task struct {
	Id        uint64                     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Status    Status                     `protobuf:"varint,3,opt,name=status,enum=task.Status" json:"status,omitempty"`
	UserId    uint64                     `protobuf:"varint,5,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

func (m *Task) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Task) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Task) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateTaskRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateTaskRequest) Reset()                    { *m = CreateTaskRequest{} }
func (m *CreateTaskRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTaskRequest) ProtoMessage()               {}
func (*CreateTaskRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateTaskRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateTaskResponse struct {
	Task *Task `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
}

func (m *CreateTaskResponse) Reset()                    { *m = CreateTaskResponse{} }
func (m *CreateTaskResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTaskResponse) ProtoMessage()               {}
func (*CreateTaskResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateTaskResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type FindTasksResponse struct {
	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks" json:"tasks,omitempty"`
}

func (m *FindTasksResponse) Reset()                    { *m = FindTasksResponse{} }
func (m *FindTasksResponse) String() string            { return proto.CompactTextString(m) }
func (*FindTasksResponse) ProtoMessage()               {}
func (*FindTasksResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FindTasksResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "task.Task")
	proto.RegisterType((*CreateTaskRequest)(nil), "task.CreateTaskRequest")
	proto.RegisterType((*CreateTaskResponse)(nil), "task.CreateTaskResponse")
	proto.RegisterType((*FindTasksResponse)(nil), "task.FindTasksResponse")
	proto.RegisterEnum("task.Status", Status_name, Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TaskService service

type TaskServiceClient interface {
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	FindTasks(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*FindTasksResponse, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	out := new(CreateTaskResponse)
	err := grpc.Invoke(ctx, "/task.TaskService/CreateTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) FindTasks(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*FindTasksResponse, error) {
	out := new(FindTasksResponse)
	err := grpc.Invoke(ctx, "/task.TaskService/FindTasks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TaskService service

type TaskServiceServer interface {
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	FindTasks(context.Context, *google_protobuf1.Empty) (*FindTasksResponse, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.TaskService/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_FindTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).FindTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.TaskService/FindTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).FindTasks(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "task.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _TaskService_CreateTask_Handler,
		},
		{
			MethodName: "FindTasks",
			Handler:    _TaskService_FindTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task/task.proto",
}

func init() { proto.RegisterFile("task/task.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xd1, 0x6a, 0xa3, 0x40,
	0x14, 0xdd, 0x31, 0xc6, 0xe0, 0x75, 0x37, 0x9b, 0xcc, 0xc3, 0x46, 0x5c, 0xd8, 0x15, 0x59, 0x58,
	0xd9, 0x07, 0x03, 0xee, 0xee, 0x43, 0xa1, 0xb4, 0x84, 0x34, 0x2d, 0x21, 0xad, 0x29, 0xc6, 0x92,
	0xc7, 0x60, 0xe2, 0x34, 0x48, 0x6a, 0xb4, 0xce, 0x58, 0xe8, 0x3f, 0xf4, 0x1f, 0xfb, 0x2b, 0x65,
	0x46, 0x93, 0x94, 0xf8, 0xd0, 0x17, 0xb9, 0xf7, 0x9e, 0x73, 0xae, 0xe7, 0x5c, 0x06, 0xbe, 0xb2,
	0x90, 0x6e, 0xfa, 0xfc, 0xe3, 0x64, 0x79, 0xca, 0x52, 0x2c, 0xf3, 0xda, 0xf8, 0xb9, 0x4e, 0xd3,
	0xf5, 0x03, 0xe9, 0x8b, 0xd9, 0xb2, 0xb8, 0xef, 0xb3, 0x38, 0x21, 0x94, 0x85, 0x49, 0x56, 0xd2,
	0x8c, 0xef, 0xc7, 0x04, 0x92, 0x64, 0xec, 0xb9, 0x04, 0xad, 0x57, 0x04, 0x72, 0x10, 0xd2, 0x0d,
	0x6e, 0x83, 0x14, 0x47, 0x3a, 0x32, 0x91, 0x2d, 0xfb, 0x52, 0x1c, 0x61, 0x0c, 0xf2, 0x36, 0x4c,
	0x88, 0x2e, 0x99, 0xc8, 0x56, 0x7d, 0x51, 0xe3, 0x5f, 0xa0, 0x50, 0x16, 0xb2, 0x82, 0xea, 0x0d,
	0x13, 0xd9, 0x6d, 0xf7, 0xb3, 0x23, 0xdc, 0xcc, 0xc4, 0xcc, 0xaf, 0x30, 0xdc, 0x83, 0x56, 0x41,
	0x49, 0xbe, 0x88, 0x23, 0xbd, 0x29, 0xd6, 0x29, 0xbc, 0x1d, 0x47, 0xf8, 0x04, 0x60, 0x95, 0x93,
	0x90, 0x91, 0x68, 0x11, 0x32, 0x5d, 0x31, 0x91, 0xad, 0xb9, 0x86, 0x53, 0xba, 0x73, 0x76, 0xee,
	0x9c, 0x60, 0x67, 0xdf, 0x57, 0x2b, 0xf6, 0x80, 0x71, 0x69, 0x91, 0x45, 0x3b, 0x69, 0xeb, 0x63,
	0x69, 0xc5, 0x1e, 0x30, 0xeb, 0x37, 0x74, 0x87, 0x62, 0x0f, 0x8f, 0xe9, 0x93, 0xc7, 0x82, 0x50,
	0xb6, 0x4f, 0x87, 0x0e, 0xe9, 0xac, 0x7f, 0x80, 0xdf, 0x13, 0x69, 0x96, 0x6e, 0x29, 0xc1, 0x3f,
	0x40, 0x9c, 0x59, 0x30, 0x35, 0x17, 0xca, 0xc4, 0x82, 0x21, 0xe6, 0xd6, 0x7f, 0xe8, 0x5e, 0xc6,
	0xdb, 0x88, 0x4f, 0xe8, 0x5e, 0x64, 0x42, 0x93, 0x83, 0x54, 0x47, 0x66, 0xe3, 0x48, 0x55, 0x02,
	0x7f, 0xce, 0x40, 0x29, 0xcf, 0x86, 0x35, 0x68, 0xdd, 0x79, 0x13, 0x6f, 0x3a, 0xf7, 0x3a, 0x9f,
	0x78, 0x33, 0x1f, 0x8c, 0x83, 0xb1, 0x77, 0xd5, 0x41, 0xa2, 0x99, 0xfa, 0x13, 0xde, 0x48, 0xf8,
	0x0b, 0xa8, 0xc3, 0xe9, 0xcd, 0xed, 0xf5, 0x28, 0x18, 0x5d, 0x74, 0x1a, 0xee, 0x0b, 0x02, 0x8d,
	0xef, 0x9b, 0x91, 0xfc, 0x29, 0x5e, 0x11, 0x7c, 0x0e, 0x70, 0x30, 0x8f, 0x7b, 0xe5, 0x0f, 0x6b,
	0xb9, 0x0d, 0xbd, 0x0e, 0x54, 0x96, 0x4f, 0x41, 0xdd, 0xe7, 0xc0, 0xdf, 0x6a, 0xa7, 0x1d, 0xf1,
	0x37, 0x63, 0x54, 0x7b, 0x6b, 0x81, 0x97, 0x8a, 0x20, 0xfe, 0x7d, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0x5e, 0x35, 0x8a, 0x31, 0xa4, 0x02, 0x00, 0x00,
}
