// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user/user.proto

It has these top-level messages:
	User
	CreateUserRequest
	CreateUserResponse
	FindUserRequest
	FindUserResponse
	VerifyUserRequest
	VerifyUserResponse
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id           uint64                     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Email        string                     `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	PasswordHash []byte                     `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	CreatedAt    *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPasswordHash() []byte {
	if m != nil {
		return m.PasswordHash
	}
	return nil
}

func (m *User) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateUserRequest struct {
	Email        string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	PasswordHash []byte `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPasswordHash() []byte {
	if m != nil {
		return m.PasswordHash
	}
	return nil
}

type CreateUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type FindUserRequest struct {
	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *FindUserRequest) Reset()                    { *m = FindUserRequest{} }
func (m *FindUserRequest) String() string            { return proto.CompactTextString(m) }
func (*FindUserRequest) ProtoMessage()               {}
func (*FindUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FindUserRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type FindUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *FindUserResponse) Reset()                    { *m = FindUserResponse{} }
func (m *FindUserResponse) String() string            { return proto.CompactTextString(m) }
func (*FindUserResponse) ProtoMessage()               {}
func (*FindUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FindUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type VerifyUserRequest struct {
	Email        string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	PasswordHash []byte `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
}

func (m *VerifyUserRequest) Reset()                    { *m = VerifyUserRequest{} }
func (m *VerifyUserRequest) String() string            { return proto.CompactTextString(m) }
func (*VerifyUserRequest) ProtoMessage()               {}
func (*VerifyUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *VerifyUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifyUserRequest) GetPasswordHash() []byte {
	if m != nil {
		return m.PasswordHash
	}
	return nil
}

type VerifyUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *VerifyUserResponse) Reset()                    { *m = VerifyUserResponse{} }
func (m *VerifyUserResponse) String() string            { return proto.CompactTextString(m) }
func (*VerifyUserResponse) ProtoMessage()               {}
func (*VerifyUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *VerifyUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user.CreateUserResponse")
	proto.RegisterType((*FindUserRequest)(nil), "user.FindUserRequest")
	proto.RegisterType((*FindUserResponse)(nil), "user.FindUserResponse")
	proto.RegisterType((*VerifyUserRequest)(nil), "user.VerifyUserRequest")
	proto.RegisterType((*VerifyUserResponse)(nil), "user.VerifyUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	FindUser(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*FindUserResponse, error)
	VerifyUser(ctx context.Context, in *VerifyUserRequest, opts ...grpc.CallOption) (*VerifyUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := grpc.Invoke(ctx, "/user.UserService/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FindUser(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*FindUserResponse, error) {
	out := new(FindUserResponse)
	err := grpc.Invoke(ctx, "/user.UserService/FindUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) VerifyUser(ctx context.Context, in *VerifyUserRequest, opts ...grpc.CallOption) (*VerifyUserResponse, error) {
	out := new(VerifyUserResponse)
	err := grpc.Invoke(ctx, "/user.UserService/VerifyUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	FindUser(context.Context, *FindUserRequest) (*FindUserResponse, error)
	VerifyUser(context.Context, *VerifyUserRequest) (*VerifyUserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/FindUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FindUser(ctx, req.(*FindUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_VerifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).VerifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/VerifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).VerifyUser(ctx, req.(*VerifyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "FindUser",
			Handler:    _UserService_FindUser_Handler,
		},
		{
			MethodName: "VerifyUser",
			Handler:    _UserService_VerifyUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xb3, 0x7d, 0xfb, 0xa2, 0x0c, 0x28, 0xb2, 0x51, 0x69, 0x7a, 0xd0, 0xa6, 0x5e, 0x1a,
	0x0f, 0x25, 0xa9, 0x5e, 0x38, 0x11, 0x63, 0x62, 0xf4, 0xc2, 0xa1, 0xfe, 0xb9, 0x92, 0x85, 0x0e,
	0xb0, 0x09, 0xd0, 0xba, 0xbb, 0x68, 0xfc, 0x0e, 0x7e, 0x32, 0x3f, 0x95, 0xe9, 0x96, 0xb5, 0x84,
	0x26, 0x86, 0x83, 0x97, 0xa6, 0x33, 0xfb, 0xf4, 0x99, 0xdf, 0x3c, 0x5d, 0x68, 0xad, 0x24, 0x8a,
	0x6e, 0xfe, 0x08, 0x33, 0x91, 0xaa, 0x94, 0xda, 0xf9, 0xbb, 0x7b, 0x3e, 0x4d, 0xd3, 0xe9, 0x1c,
	0xbb, 0xba, 0x37, 0x5a, 0x4d, 0xba, 0x8a, 0x2f, 0x50, 0x2a, 0xb6, 0xc8, 0x0a, 0x99, 0xff, 0x49,
	0xc0, 0x7e, 0x96, 0x28, 0xe8, 0x21, 0x58, 0x3c, 0x71, 0x88, 0x47, 0x02, 0x3b, 0xb6, 0x78, 0x42,
	0x8f, 0xe1, 0x3f, 0x2e, 0x18, 0x9f, 0x3b, 0x96, 0x47, 0x82, 0x7a, 0x5c, 0x14, 0xf4, 0x02, 0x0e,
	0x32, 0x26, 0xe5, 0x7b, 0x2a, 0x92, 0xe1, 0x8c, 0xc9, 0x99, 0xf3, 0xcf, 0x23, 0x41, 0x33, 0x6e,
	0x9a, 0xe6, 0x3d, 0x93, 0x33, 0xda, 0x03, 0x18, 0x0b, 0x64, 0x0a, 0x93, 0x21, 0x53, 0x8e, 0xed,
	0x91, 0xa0, 0x11, 0xb9, 0x61, 0x41, 0x12, 0x1a, 0x92, 0xf0, 0xc9, 0x90, 0xc4, 0xf5, 0xb5, 0xfa,
	0x46, 0xf9, 0x03, 0x68, 0xdf, 0xea, 0x22, 0x67, 0x8a, 0xf1, 0x75, 0x85, 0x52, 0x95, 0x28, 0xe4,
	0x57, 0x14, 0xab, 0x8a, 0xe2, 0x5f, 0x03, 0xdd, 0xf4, 0x93, 0x59, 0xba, 0x94, 0x48, 0xcf, 0x40,
	0xa7, 0xa3, 0xfd, 0x1a, 0x11, 0x84, 0x3a, 0x36, 0xad, 0xd0, 0x7d, 0xff, 0x12, 0x5a, 0x77, 0x7c,
	0x99, 0x6c, 0x32, 0x74, 0x60, 0x2f, 0x3f, 0x1a, 0xfe, 0x64, 0x54, 0xcb, 0xcb, 0x87, 0xc4, 0x8f,
	0xe0, 0xa8, 0xd4, 0xee, 0xe8, 0x3f, 0x80, 0xf6, 0x0b, 0x0a, 0x3e, 0xf9, 0xf8, 0xbb, 0x2d, 0x37,
	0xfd, 0x76, 0xa3, 0x88, 0xbe, 0x08, 0x34, 0xf2, 0xf2, 0x11, 0xc5, 0x1b, 0x1f, 0x23, 0xed, 0x03,
	0x94, 0x59, 0xd1, 0x4e, 0xa1, 0xaf, 0xfc, 0x0d, 0xd7, 0xa9, 0x1e, 0xac, 0x07, 0xf6, 0x60, 0xdf,
	0x44, 0x41, 0x4f, 0x0a, 0xd5, 0x56, 0x8c, 0xee, 0xe9, 0x76, 0x7b, 0xfd, 0x69, 0x1f, 0xa0, 0xdc,
	0xc0, 0xcc, 0xae, 0x64, 0x64, 0x66, 0x57, 0x97, 0x1d, 0xd5, 0xf4, 0xbd, 0xba, 0xfa, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x9d, 0x9b, 0x4f, 0x02, 0x08, 0x03, 0x00, 0x00,
}
